# This Dockerfile builds the API only.

FROM python:3.6
WORKDIR /app

COPY backendWithFlask/requirements.txt backendWithFlask/app.py backendWithFlask/.flaskenv ./
RUN pip install -r ./requirements.txt
ENV FLASK_ENV production

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "api:app"]